spring:
  datasource:
    url: jdbc:mysql://8.136.6.137:3306/marx
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 8.136.6.137
    port: 6379
    password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB

mybatis:
  type-aliases-package: com.marx.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

marx:
  name: 马克思管理学院
  version: 1.0
  file:
  staticAccessPath: /file/**
  uploadFolder: ./file/
server:
  port: 1315

logging:
  level:
    com.marx: debug
